apiVersion: v1
kind: Pod
metadata:
  name: nginx-emptydir
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: emptydir-volume
          mountPath: /usr/share/nginx/html

  volumes:
    - name: emptydir-volume
      emptyDir: {}