apiVersion: v1
kind: Service
metadata:
  name: statefulset-service
spec:
  selector:
    app: statefulset-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: statefulset-headless
spec:
  clusterIP: None
  selector:
    app: statefulset-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: statefulset-example
spec:
  serviceName: "statefulset-headless"
  replicas: 3
  selector:
    matchLabels:
      app: statefulset-app
  template:
    metadata:
     name: statefulset-pod
     labels:
        app: statefulset-app
    spec:
      containers:
      - name: statefulset-container
        image: busybox
        command: [ "sleep", "3600" ]
        volumeMounts:
        - name: statefulset-volume
          mountPath: "/mnt/statefulset"
      volumes:
      - name: statefulset-volume
        persistentVolumeClaim:
          claimName: statefulset-pvc
    