apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-pvc
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  csi:
     driver: local.csi.k8s.io
     volumeHandle: statefulset-volume
     fsType: ext4