apiVersion: v1
kind : Pod
metadata:
  name: roboshop-pod
  namespace: roboshop
  labels:
    project : roboshop
    environment: dev
    spec:
      containers:
        - name: roboshop-container
          image: nginx:latest
          ports:
            - containerPort: 80