apiVersion: apps/v1
kind : Deployment
metadata :
  name : roboshop-pod
  labels :
    project: roboshop
    environment: dev
spec :
  replicas : 2
  selector :
    matchLabels :
      project: roboshop
      environment: dev
  template :
    metadata :
      labels :
        project: roboshop
        environment: dev
    spec :
      containers :
        - name : roboshop-pod
          image : nginx:latest
          ports :
            - containerPort : 80