apiVersion: v1
kind : pod
metadata : 
   name : roboshop-config-pod
spec :
      containers :
        - name : roboshop-cofig 
          image : nginx:latest
          envFrom :
            - configMapRef :
                name : roboshop-config
